apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 0debt

resources:
  - 00-namespace.yaml
  - 01-secrets.yaml
  - 02-configmap.yaml
  - 03-mongo.yaml
  - 04-redis.yaml
  - 05-users-service.yaml
  - 06-groups-service.yaml
  - 07-expenses-service.yaml
  - 08-analytics-service.yaml
  - 09-notifications-service.yaml
  - 10-api-gateway.yaml
  - 11-frontend.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: 0debt
